//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookids
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animadores : Pessoas
    {
        public Animadores()
        {
            this.Colaboracoes = new HashSet<Colaboracoes>();
        }
    
        public string Especialidade { get; set; }
    
        public virtual ICollection<Colaboracoes> Colaboracoes { get; set; }
    }
}
