//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookids
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes : Pessoas
    {
        public Clientes()
        {
            this.Compras = new HashSet<Compras>();
        }
    
        public decimal ValorOferta { get; set; }
        public int NrCartao { get; set; }
    
        public virtual ICollection<Compras> Compras { get; set; }
    }
}
