//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookids
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        public Compras()
        {
            this.DetalheCompras = new HashSet<DetalheCompras>();
        }
    
        public System.DateTime Data { get; set; }
        public bool UtilizouCartao { get; set; }
        public int NrCompra { get; set; }
        public int IdCliente { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual ICollection<DetalheCompras> DetalheCompras { get; set; }
    }
}
