//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookids
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filhos : Pessoas
    {
        public Filhos()
        {
            this.Inscricoes = new HashSet<Inscricoes>();
        }
    
        public string Sexo { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public int IdProgenitor { get; set; }
        public int EscolasIdEscola { get; set; }
    
        public virtual ICollection<Inscricoes> Inscricoes { get; set; }
        public virtual Escolas Escolas { get; set; }
    }
}
