//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookids
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloBookidsContainer : DbContext
    {
        public ModeloBookidsContainer()
            : base("name=ModeloBookidsContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public DbSet<Clientes> ClientesSet { get; set; }
        public DbSet<Pessoas> PessoasSet { get; set; }
        public DbSet<Inscricoes> InscricoesSet { get; set; }
        public DbSet<Eventos> EventosSet { get; set; }
        public DbSet<Colaboracoes> ColaboracoesSet { get; set; }
        public DbSet<Participacoes> ParticipacoesSet { get; set; }
        public DbSet<Escolas> EscolasSet { get; set; }
        public DbSet<Compras> ComprasSet { get; set; }
        public DbSet<DetalheCompras> DetalheComprasSet { get; set; }
        public DbSet<Produtos> ProdutosSet { get; set; }
        public DbSet<TipoProduto> TipoProdutoSet1 { get; set; }
    }
}
